# ─────────────────────────────────────────────
#  Chef Burger — Full Menu Data
# ─────────────────────────────────────────────

CATEGORIES = {
    "burgers":  "🍔 Burgers",
    "chicken":  "🍗 Chicken",
    "sides":    "🍟 Sides",
    "drinks":   "🥤 Drinks",
    "desserts": "🍰 Desserts",
    "combos":   "🎁 Combos",
}

MENU = [
    # ── BURGERS ──
    {
        "id": 1,
        "name": "The Classic",
        "category": "burgers",
        "description": "Beef patty, cheddar, lettuce, tomato, gherkins, special sauce, brioche bun",
        "price": 32000,
        "prep_time": 10,
        "badges": ["Most Popular"],
        "allergens": ["Gluten", "Dairy", "Egg"],
        "calories": 620,
    },
    {
        "id": 2,
        "name": "Double Smash",
        "category": "burgers",
        "description": "Two smashed patties, American cheese, caramelised onions, pickles, smash sauce",
        "price": 48000,
        "prep_time": 12,
        "badges": ["Most Popular"],
        "allergens": ["Gluten", "Dairy"],
        "calories": 890,
    },
    {
        "id": 3,
        "name": "Chef's Signature",
        "category": "burgers",
        "description": "Wagyu blend, truffle mayo, aged cheddar, wild arugula, red onion jam, black bun",
        "price": 62000,
        "prep_time": 14,
        "badges": ["Chef's Choice", "Premium"],
        "allergens": ["Gluten", "Dairy", "Egg"],
        "calories": 750,
    },
    {
        "id": 4,
        "name": "Spicy Inferno",
        "category": "burgers",
        "description": "Beef patty, jalapeños, sriracha mayo, pepper jack cheese, crispy bacon, ghost chilli",
        "price": 38000,
        "prep_time": 11,
        "badges": ["New", "Hot"],
        "allergens": ["Gluten", "Dairy"],
        "calories": 710,
    },
    {
        "id": 5,
        "name": "Mushroom Melt",
        "category": "burgers",
        "description": "Beef patty, sautéed mushrooms, swiss cheese, garlic aioli, caramelised onions",
        "price": 36000,
        "prep_time": 12,
        "badges": ["Chef's Choice"],
        "allergens": ["Gluten", "Dairy", "Egg"],
        "calories": 660,
    },
    {
        "id": 6,
        "name": "BBQ Stack",
        "category": "burgers",
        "description": "Beef patty, pulled pork, house BBQ sauce, crispy onion strings, smoked cheddar",
        "price": 52000,
        "prep_time": 13,
        "badges": ["Chef's Choice"],
        "allergens": ["Gluten", "Dairy"],
        "calories": 820,
    },
    {
        "id": 7,
        "name": "Veggie Supreme",
        "category": "burgers",
        "description": "House-made black bean patty, avocado, roasted peppers, feta, tzatziki",
        "price": 30000,
        "prep_time": 10,
        "badges": ["Vegetarian"],
        "allergens": ["Gluten", "Dairy", "Egg"],
        "calories": 540,
    },

    # ── CHICKEN ──
    {
        "id": 8,
        "name": "Crispy Chicken",
        "category": "chicken",
        "description": "Double-fried chicken breast, coleslaw, pickles, honey mustard, potato bun",
        "price": 34000,
        "prep_time": 12,
        "badges": ["Fan Favourite"],
        "allergens": ["Gluten", "Dairy", "Egg"],
        "calories": 680,
    },
    {
        "id": 9,
        "name": "Nashville Hot",
        "category": "chicken",
        "description": "Spiced fried chicken, hot cayenne butter, pickles, white bread — Nashville style",
        "price": 36000,
        "prep_time": 13,
        "badges": ["Hot"],
        "allergens": ["Gluten", "Dairy"],
        "calories": 720,
    },
    {
        "id": 10,
        "name": "Grilled Chicken",
        "category": "chicken",
        "description": "Marinated grilled chicken, avocado, rocket, sun-dried tomato, lemon aioli",
        "price": 34000,
        "prep_time": 14,
        "badges": ["Healthy"],
        "allergens": ["Gluten", "Egg"],
        "calories": 490,
    },

    # ── SIDES ──
    {
        "id": 11,
        "name": "Signature Fries",
        "category": "sides",
        "description": "Double-fried, seasoned with our house spice blend, served with dip",
        "price": 14000,
        "prep_time": 7,
        "badges": [],
        "allergens": ["Gluten"],
        "calories": 380,
    },
    {
        "id": 12,
        "name": "Loaded Fries",
        "category": "sides",
        "description": "Fries topped with cheddar sauce, bacon bits, jalapeños, sour cream",
        "price": 22000,
        "prep_time": 10,
        "badges": ["Most Popular"],
        "allergens": ["Gluten", "Dairy"],
        "calories": 580,
    },
    {
        "id": 13,
        "name": "Onion Rings",
        "category": "sides",
        "description": "Beer-battered, golden and crispy, served with ranch dipping sauce",
        "price": 16000,
        "prep_time": 8,
        "badges": [],
        "allergens": ["Gluten", "Dairy", "Egg"],
        "calories": 420,
    },
    {
        "id": 14,
        "name": "Coleslaw",
        "category": "sides",
        "description": "House-made creamy coleslaw with apple and fennel",
        "price": 10000,
        "prep_time": 2,
        "badges": [],
        "allergens": ["Egg"],
        "calories": 180,
    },
    {
        "id": 15,
        "name": "Mac & Cheese Bites",
        "category": "sides",
        "description": "Crispy-coated mac & cheese bites, 6 pieces, with truffle dip",
        "price": 18000,
        "prep_time": 8,
        "badges": ["New"],
        "allergens": ["Gluten", "Dairy", "Egg"],
        "calories": 460,
    },

    # ── DRINKS ──
    {
        "id": 16,
        "name": "Craft Lemonade",
        "category": "drinks",
        "description": "Fresh-squeezed with mint and a hint of ginger. Refillable.",
        "price": 12000,
        "prep_time": 3,
        "badges": ["House Made"],
        "allergens": [],
        "calories": 140,
    },
    {
        "id": 17,
        "name": "Milkshake",
        "category": "drinks",
        "description": "Thick and creamy. Choose: Vanilla, Chocolate, Strawberry, Salted Caramel",
        "price": 18000,
        "prep_time": 5,
        "badges": ["Fan Favourite"],
        "allergens": ["Dairy"],
        "calories": 520,
    },
    {
        "id": 18,
        "name": "Soft Drink",
        "category": "drinks",
        "description": "Pepsi, 7UP, Mirinda, Mountain Dew — 500ml can",
        "price": 7000,
        "prep_time": 1,
        "badges": [],
        "allergens": [],
        "calories": 170,
    },
    {
        "id": 19,
        "name": "Water",
        "category": "drinks",
        "description": "Still or sparkling — 500ml",
        "price": 5000,
        "prep_time": 1,
        "badges": [],
        "allergens": [],
        "calories": 0,
    },

    # ── DESSERTS ──
    {
        "id": 20,
        "name": "Cookie Dough Sundae",
        "description": "Warm cookie dough, vanilla ice cream, chocolate drizzle, crushed Oreo",
        "category": "desserts",
        "price": 20000,
        "prep_time": 6,
        "badges": ["New"],
        "allergens": ["Gluten", "Dairy", "Egg"],
        "calories": 640,
    },
    {
        "id": 21,
        "name": "Churros & Dip",
        "description": "Golden churros, dusted with cinnamon sugar, with chocolate dipping sauce",
        "category": "desserts",
        "price": 16000,
        "prep_time": 8,
        "badges": [],
        "allergens": ["Gluten", "Dairy", "Egg"],
        "calories": 480,
    },

    # ── COMBOS ──
    {
        "id": 22,
        "name": "Classic Combo",
        "description": "The Classic burger + Signature Fries + Soft Drink. Save 8,000 UZS vs buying separately.",
        "category": "combos",
        "price": 45000,
        "prep_time": 12,
        "badges": ["Best Value"],
        "allergens": ["Gluten", "Dairy"],
        "calories": 1170,
    },
    {
        "id": 23,
        "name": "Double Trouble Combo",
        "description": "Double Smash + Loaded Fries + Milkshake. The full experience.",
        "category": "combos",
        "price": 78000,
        "prep_time": 14,
        "badges": ["Most Popular"],
        "allergens": ["Gluten", "Dairy"],
        "calories": 1990,
    },
    {
        "id": 24,
        "name": "Chicken Combo",
        "description": "Crispy Chicken + Onion Rings + Craft Lemonade.",
        "category": "combos",
        "price": 54000,
        "prep_time": 13,
        "badges": ["Best Value"],
        "allergens": ["Gluten", "Dairy", "Egg"],
        "calories": 1280,
    },
]
